apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: consoleapp
spec:
    schedule: "*/1 * * * *"
    jobTemplate:
        spec:
          template:
              spec:
                containers:
                - name: consoleapp
                  image: haripraghash/consoleapp:1.1
                  imagePullPolicy: Never
                  command: ["dotnet", "ConsoleApp.dll"]
                restartPolicy: OnFailure